context_and_goal: | 
  This is a regression task for the bike dataset.
  The goal is to predict the number of bike rentals based on various features such as weather conditions, time of day, and other relevant factors.
  Here are some details about the features found in the dataset:
  {
    "season": "season (1:springer, 2:summer, 3:fall, 4:winter)",
    "yr": "year (0: 2011, 1:2012)",
    "mnth": "month ( 1 to 12)",
    "hr": "hour (0 to 23)",
    "holiday": "whether day is holiday or not",
    "weekday": "day of the week",
    "workingday": "if day is neither weekend nor holiday is 1, otherwise is 0.",
    "weathersit": "1: Clear, Few clouds, Partly cloudy, Partly cloudy, 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist, 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds, 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog",
    "temp": "Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)",
    "atemp": "Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)",
    "hum": "Normalized humidity. The values are divided to 100 (max)",
    "windspeed": "Normalized wind speed. The values are divided to 67 (max)"
  }

experiment_description: Feature assessment for the bike dataset.
experiment_name: bike
feature_file_path: /workspace/tasks/regression/bike/data.csv
knowledge_db_collection_name: bike
knowledge_db_path: /workspace/chroma_db/bike_knowledge_db
label_file_path: /workspace/tasks/regression/bike/labels.csv
modality: tabular
task_type: regression
output_dir: /workspace/tasks/regression/bike/output
