context_and_goal: |
  This is a regression task for the crab dataset.
  The goal is to predict the age of crabs based on various physical measurements and characteristics.
  Here are some details about the features found in the dataset:
  {
    "Sex": "Gender of the Crab - Male, Female and Indeterminate.",
    "Length": "Length of the Crab (in Feet; 1 foot = 30.48 cms)",
    "Diameter": "Diameter of the Crab (in Feet; 1 foot = 30.48 cms)",
    "Height": "Height of the Crab (in Feet; 1 foot = 30.48 cms)",
    "Weight": "Weight of the Crab (in ounces; 1 Pound = 16 ounces)",
    "Shucked Weight": "Weight without the shell (in ounces; 1 Pound = 16 ounces)",
    "Viscera Weight": "is weight that wraps around your abdominal organs deep inside body (in ounces; 1 Pound = 16 ounces)",
    "Shell Weight": "Weight of the Shell (in ounces; 1 Pound = 16 ounces)"
  }
experiment_description: Feature assessment for the crab dataset.
experiment_name: crab
feature_file_path: /workspace/tasks/regression/crab/data.csv
knowledge_db_collection_name: crab
knowledge_db_path: /workspace/chroma_db/crab_knowledge_db
label_file_path: /workspace/tasks/regression/crab/labels.csv
modality: tabular
output_dir: /workspace/tasks/regression/crab/output
task_type: regression
