context_and_goal: |
  This is a classification task on the heart dataset.
  The goal is to predict the presence of heart disease in patients based on various medical features (yes/no).
  Here are some details about the features found in the dataset:
  {
    "Age": "age of the patient",
    "Sex": "sex of the patient",
    "ChestPainType": "chest pain type",
    "RestingBP": "resting blood pressure [mm Hg]",
    "Cholesterol": "serum cholesterol [mm/dl]",
    "FastingBS": "fasting blood sugar [1: if FastingBS > 120 mg/dl, 0: otherwise]",
    "RestingECG": "resting electrocardiogram results",
    "MaxHR": "maximum heart rate achieved",
    "ExerciseAngina": "exercise-induced angina",
    "Oldpeak": "oldpeak = ST [Numeric value measured in depression]",
    "ST_Slope": "the slope of the peak exercise ST segment"
  }
experiment_description: Feature assessment for the heart dataset.
experiment_name: heart
feature_file_path: /workspace/tasks/classification/heart/data.csv
knowledge_db_collection_name: heart
knowledge_db_path: /workspace/chroma_db/heart_knowledge_db
label_file_path: /workspace/tasks/classification/heart/labels.csv
output_dir: /workspace/tasks/classification/heart/output
modality: tabular
task_type: classification