context_and_goal: | 
  This is a classification task on the vehicle dataset.
  The goal is to classify different types of vehicles based on various shape and size features. 
  Here are some details about the features found in the dataset:
    "COMPACTNESS": "(average perim)**2/area",
    "CIRCULARITY": "(average radius)**2/area",
    "DISTANCE CIRCULARITY": "area/(av.distance from border)**2",
    "RADIUS RATIO": "(max.rad-min.rad)/av.radius",
    "PR.AXIS ASPECT RATIO": "(minor axis)/(major axis)",
    "MAX.LENGTH ASPECT RATIO": "(length perp. max length)/(max length)",
    "SCATTER RATIO": "(inertia about minor axis)/(inertia about major axis)",
    "ELONGATEDNESS": "area/(shrink width)**2",
    "PR.AXIS EQUIVALENT DIAMETER": "sqrt(4*area/(pi))",
    "MAX.LENGTH EQUIVALENT DIAMETER": "sqrt(4*area/(pi))",
    "PR.AXIS RECTANGULARITY": "area/(pr.axis length*pr.axis width)",
    "MAX.LENGTH RECTANGULARITY": "area/(max.length*length perp. to this)",
    "SCALED VARIANCE ALONG MAJOR AXIS": "(2nd order moment about minor axis)/area",
    "SCALED VARIANCE ALONG MINOR AXIS": "(2nd order moment about major axis)/area",
    "SCALED RADIUS OF GYRATION": "(mavar+mivar)/area",
    "SKEWNESS ABOUT MAJOR AXIS": "(3rd order moment about major axis)/sigma_min**3",
    "SKEWNESS ABOUT MINOR AXIS": "(3rd order moment about minor axis)/sigma_maj**3",
    "KURTOSIS ABOUT MINOR AXIS": "(4th order moment about major axis)/sigma_min**4",
    "KURTOSIS ABOUT MAJOR AXIS": "(4th order moment about minor axis)/sigma_maj**4",
    "HOLLOWS RATIO": "(area of hollows)/(area of bounding polygon)"
  
experiment_description: Feature assessment for the vehicle dataset.
experiment_name: vehicle
feature_file_path: /workspace/tasks/classification/vehicle/data.csv
knowledge_db_collection_name: vehicle
knowledge_db_path: /workspace/chroma_db/vehicle_knowledge_db
label_file_path: /workspace/tasks/classification/vehicle/labels.csv
output_dir: /workspace/tasks/classification/vehicle/output
modality: tabular
task_type: classification