context_and_goal: | 
  This is a regression task for the wine dataset.
  The goal is to predict the quality of wine based on various chemical properties and characteristics.
  Here are some details about the features found in the dataset:
  {
    "fixed acidity": "fixed acidity of the wine",
    "volatile acidity": "volatile acidity of the wine",
    "citric acid": "citric acid of the wine",
    "residual sugar": "residual sugar of the wine",
    "chlorides": "chlorides of the wine",
    "free sulfur dioxide": "free sulfur dioxide of the wine",
    "total sulfur dioxide": "total sulfur dioxide of the wine",
    "density": "density of the wine",
    "pH": "pH of the wine",
    "sulphates": "sulphates of the wine",
    "alcohol": "alcohol of the wine",
    "color": "color of the wine"
  }
experiment_description: Feature assessment for the wine dataset.
experiment_name: wine
feature_file_path: /workspace/tasks/regression/wine/data.csv
knowledge_db_collection_name: wine
knowledge_db_path: /workspace/chroma_db/wine_knowledge_db
label_file_path: /workspace/tasks/regression/wine/labels.csv
modality: tabular
output_dir: /workspace/tasks/regression/wine/output
task_type: regression
