context_and_goal: "\n            This is a classification task. \n            Here\
  \ are some details about the features found in the dataset:\n            {\n   \
  \ \"AGE\": \"Age\",\n    \"SEX\": \"Gender\",\n    \"INF_ANAM\": \"Quantity of myocardial\
  \ infarctions in the anamnesis\",\n    \"STENOK_AN\": \"Exertional angina pectoris\
  \ in the anamnesis\",\n    \"FK_STENOK\": \"Functional class of angina pectoris\
  \ in the last year\",\n    \"IBS_POST\": \"Coronary heart disease in recent weeks,\
  \ days before admission to hospital\",\n    \"GB\": \"Presence of an essential hypertension\"\
  ,\n    \"SIM_GIPERT\": \"Symptomatic hypertension\",\n    \"DLIT_AG\": \"Duration\
  \ of arterial hypertension\",\n    \"ZSN_A\": \"Presence of chronic Heart failure\
  \ in the anamnesis\",\n    \"nr_11\": \"Observing of arrhythmia in the anamnesis\"\
  ,\n    \"nr_01\": \"Premature atrial contractions in the anamnesis\",\n    \"nr_02\"\
  : \"Premature ventricular contractions in the anamnesis\",\n    \"nr_03\": \"Paroxysms\
  \ of atrial fibrillation in the anamnesis\",\n    \"nr_04\": \"A persistent form\
  \ of atrial fibrillation in the anamnesis\",\n    \"nr_07\": \"Ventricular fibrillation\
  \ in the anamnesis\",\n    \"nr_08\": \"Ventricular paroxysmal tachycardia in the\
  \ anamnesis\",\n    \"np_01\": \"First-degree AV block in the anamnesis\",\n   \
  \ \"np_04\": \"Third-degree AV block in the anamnesis\",\n    \"np_05\": \"LBBB\
  \ (anterior branch) in the anamnesis\",\n    \"np_07\": \"Incomplete LBBB in the\
  \ anamnesis\",\n    \"np_08\": \"Complete LBBB in the anamnesis\",\n    \"np_09\"\
  : \"Incomplete RBBB in the anamnesis\",\n    \"np_10\": \"Complete RBBB in the anamnesis\"\
  ,\n    \"endocr_01\": \"Diabetes mellitus in the anamnesis\",\n    \"endocr_02\"\
  : \"Obesity in the anamnesis\",\n    \"endocr_03\": \"Thyrotoxicosis in the anamnesis\"\
  ,\n    \"zab_leg_01\": \"Chronic bronchitis in the anamnesis\",\n    \"zab_leg_02\"\
  : \"chronic bronchitis in the anamnesis\",\n    \"zab_leg_03\": \"Bronchial asthma\
  \ in the anamnesis\",\n    \"zab_leg_04\": \"Chronic pneumonia in the anamnesis\"\
  ,\n    \"zab_leg_06\": \"Pulmonary tuberculosis in the anamnesis\",\n    \"S_AD_ORIT\"\
  : \"Systolic blood pressure according to intensive care unit\",\n    \"D_AD_ORIT\"\
  : \"Diastolic blood pressure according to intensive care unit\",\n    \"O_L_POST\"\
  : \"Pulmonary edema at the time of admission to intensive care unit\",\n    \"K_SH_POST\"\
  : \"Cardiogenic shock at the time of admission to intensive care unit\",\n    \"\
  MP_TP_POST\": \"Paroxysms of atrial fibrillation at the time of admission to intensive\
  \ care unit, or at a prehospital stage\",\n    \"SVT_POST\": \"Paroxysms of supraventricular\
  \ tachycardia at the time of admission to intensive care unit\",\n    \"GT_POST\"\
  : \"Paroxysms of ventricular tachycardia at the time of admission to intensive care\
  \ unit\",\n    \"FIB_G_POST\": \"Ventricular fibrillation at the time of admission\
  \ to intensive care unit\",\n    \"ant_im\": \"Presence of an anterior myocardial\
  \ infarction (left ventricular, ECG changes in leads V1 \\u2013 V4)\",\n    \"lat_im\"\
  : \"Presence of a lateral myocardial infarction (left ventricular, ECG changes in\
  \ leads V5 \\u2013 V6, I, AVL)\",\n    \"inf_im\": \"Presence of an inferior myocardial\
  \ infarction (left ventricular, ECG changes in leads III, AVF, II.)\",\n    \"post_im\"\
  : \"Presence of a posterior myocardial infarction (left ventricular, ECG changes\
  \ in V7 \\u2013 V9, reciprocity changes in leads V1 \\u2013 V3)\",\n    \"IM_PG_P\"\
  : \"Presence of a right ventricular myocardial infarction\",\n    \"ritm_ecg_p_01\"\
  : \"ECG rhythm at the time of admission to hospital \\u2013 sinus with a heart rate\
  \ 60-90\",\n    \"ritm_ecg_p_02\": \"ECG rhythm at the time of admission to hospital\
  \ \\u2013 atrial fibrillation\",\n    \"ritm_ecg_p_04\": \"ECG rhythm at the time\
  \ of admission to hospital \\u2013 atrial\",\n    \"ritm_ecg_p_06\": \"ECG rhythm\
  \ at the time of admission to hospital \\u2013 idioventricular\",\n    \"ritm_ecg_p_07\"\
  : \"ECG rhythm at the time of admission to hospital \\u2013 sinus with a heart rate\
  \ above 90\",\n    \"ritm_ecg_p_08\": \"ECG rhythm at the time of admission to hospital\
  \ \\u2013 sinus with a heart rate below 60\",\n    \"n_r_ecg_p_01\": \"Premature\
  \ atrial contractions on ECG at the time of admission to hospital\",\n    \"n_r_ecg_p_02\"\
  : \"Frequent premature atrial contractions on ECG at the time of admission to hospital\"\
  ,\n    \"n_r_ecg_p_03\": \"ventricular contractions on ECG at the time of admission\
  \ to hospital\",\n    \"n_r_ecg_p_04\": \"Frequent premature ventricular contractions\
  \ on ECG at the time of admission to hospital\",\n    \"n_r_ecg_p_05\": \"Paroxysms\
  \ of atrial fibrillation on ECG at the time of admission to hospital\",\n    \"\
  n_r_ecg_p_06\": \"Persistent form of atrial fibrillation on ECG at the time of admission\
  \ to hospital\",\n    \"n_r_ecg_p_08\": \"Paroxysms of supraventricular tachycardia\
  \ on ECG at the time of admission to hospital\",\n    \"n_r_ecg_p_09\": \"Paroxysms\
  \ of ventricular tachycardia on ECG at the time of admission to hospital\",\n  \
  \  \"n_r_ecg_p_10\": \"Ventricular fibrillation on ECG at the time of admission\
  \ to hospital\",\n    \"n_p_ecg_p_01\": \"Sinoatrial block on ECG at the time of\
  \ admission to hospital\",\n    \"n_p_ecg_p_03\": \"First-degree AV block on ECG\
  \ at the time of admission to hospital\",\n    \"n_p_ecg_p_04\": \"Type 1 Second-degree\
  \ AV block (Mobitz I/Wenckebach) on ECG at the time of admission to hospital\",\n\
  \    \"n_p_ecg_p_05\": \"Type 2 Second-degree AV block (Mobitz II/Hay) on ECG at\
  \ the time of admission to hospital\",\n    \"n_p_ecg_p_06\": \"Third-degree AV\
  \ block on ECG at the time of admission to hospital\",\n    \"n_p_ecg_p_07\": \"\
  LBBB (anterior branch) on ECG at the time of admission to hospital\",\n    \"n_p_ecg_p_08\"\
  : \"LBBB (anterior branch) on ECG at the time of admission to hospital\",\n    \"\
  n_p_ecg_p_09\": \"Incomplete LBBB on ECG at the time of admission to hospital\"\
  ,\n    \"n_p_ecg_p_10\": \"Complete LBBB on ECG at the time of admission to hospital\"\
  ,\n    \"n_p_ecg_p_11\": \"Incomplete RBBB on ECG at the time of admission to hospital\"\
  ,\n    \"n_p_ecg_p_12\": \"Complete RBBB on ECG at the time of admission to hospital\"\
  ,\n    \"fibr_ter_01\": \"Fibrinolytic therapy by Celiasum 750k IU\",\n    \"fibr_ter_02\"\
  : \"Fibrinolytic therapy by Celiasum 1m IU\",\n    \"fibr_ter_03\": \"Fibrinolytic\
  \ therapy by Celiasum 3m IU\",\n    \"fibr_ter_05\": \"Fibrinolytic therapy by Streptase\"\
  ,\n    \"fibr_ter_06\": \"Fibrinolytic therapy by Celiasum 500k IU\",\n    \"fibr_ter_07\"\
  : \"Fibrinolytic therapy by Celiasum 250k IU\",\n    \"fibr_ter_08\": \"Fibrinolytic\
  \ therapy by Streptodecase 1.5m IU\",\n    \"ALT_BLOOD\": \"Serum AlAT content\"\
  ,\n    \"AST_BLOOD\": \"Serum AsAT content\",\n    \"L_BLOOD\": \"White blood cell\
  \ count (billions per liter)\",\n    \"ROE\": \"Erythrocyte sedimentation rate\"\
  ,\n    \"TIME_B_S\": \"Time elapsed from the beginning of the attack of CHD to the\
  \ hospital\",\n    \"NITR_S\": \"Use of liquid nitrates in the ICU\",\n    \"LID_S_n\"\
  : \"Use of lidocaine in the ICU\",\n    \"B_BLOK_S_n\": \"Use of beta-blockers in\
  \ the ICU\",\n    \"ANT_CA_S_n\": \"Use of calcium channel blockers in the ICU\"\
  ,\n    \"GEPAR_S_n\": \"Use of \\u0430 anticoagulants in the ICU\",\n    \"ASP_S_n\"\
  : \"Use of acetylsalicylic acid in the ICU\",\n    \"TIKL_S_n\": \"Use of Ticlid\
  \ in the ICU\",\n    \"TRENT_S_n\": \"Use of Trental in the ICU\",\n    \"ZSN\"\
  : \"Chronic heart failure\"\n}\n        "
experiment_description: Feature assessment for the myocardial dataset.
experiment_name: myocardial
feature_file_path: /workspace/tasks/classification/myocardial/data.csv
knowledge_db_collection_name: myocardial
knowledge_db_path: /workspace/chroma_db/myocardial_knowledge_db
label_file_path: /workspace/tasks/classification/myocardial/labels.csv
output_dir: /workspace/tasks/classification/myocardial/output
modality: tabular
task_type: classification