context_and_goal: |
  This is a regression task for the housing dataset.
  The goal is to predict the median house value based on various features such as location, size, and other relevant factors.
  Here are some details about the features found in the dataset:
  {
    "longitude": "A measure of how far west a house is; a higher value is farther west",
    "latitude": "A measure of how far north a house is; a higher value is farther north",
    "housing_median_age": "Median age of a house within a block; a lower number is a newer building",
    "total_rooms": "Total number of rooms within a block",
    "total_bedrooms": "Total number of bedrooms within a block",
    "population": "Total number of people residing within a block",
    "households": "Total number of households, a group of people residing within a home unit, for a block",
    "median_income": "Median income for households within a block of houses (measured in tens of thousands of US Dollars)",
    "ocean_proximity": "Location of the house w.r.t ocean/sea"
  }
experiment_description: Feature assessment for the housing dataset.
experiment_name: housing
feature_file_path: /workspace/tasks/regression/housing/data.csv
knowledge_db_collection_name: housing
knowledge_db_path: /workspace/chroma_db/housing_knowledge_db
label_file_path: /workspace/tasks/regression/housing/labels.csv
modality: tabular
output_dir: /workspace/tasks/regression/housing/output
task_type: regression
