context_and_goal: |
  This is a regression task for the forest-fires dataset from Portugal.
  The goal is to predict the area affected by forest fires based on various meteorological and spatial features.
  Here are some details about the features found in the dataset:
  {
    "X": "x-axis spatial coordinate within the Montesinho park map",
    "Y": "y-axis spatial coordinate within the Montesinho park map",
    "month": "month of the year",
    "day": "day of the week",
    "FFMC": "FFMC index from the FWI system",
    "DMC": "DMC index from the FWI system",
    "DC": "DC index from the FWI system",
    "ISI": "ISI index from the FWI system",
    "temp": "temperature in Celsius degrees",
    "RH": "relative humidity in %",
    "wind": "wind speed in km/h",
    "rain": "outside rain in mm/m2",
  }
experiment_description: Feature assessment for the forest-fires dataset.
experiment_name: forest-fires
feature_file_path: /workspace/tasks/regression/forest-fires/data.csv
knowledge_db_collection_name: forest-fires
knowledge_db_path: /workspace/chroma_db/forest-fires_knowledge_db
label_file_path: /workspace/tasks/regression/forest-fires/labels.csv
modality: tabular
output_dir: /workspace/tasks/regression/forest-fires/output
task_type: regression
